server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://8.129.47.98:3306/cloud_order?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: a1318587732A
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 8.129.47.98:8848 # nacos地址
      discovery:
        cluster-name: HZ # 集群名称
        ephemeral: false # 是否临时注册
mybatis:
  type-aliases-package: cn.shaw.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.shaw: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka/ # 服务注册中心地址
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#userservice:
#  ribbon: # ribbon负载均衡
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 随机策略
ribbon:
  eager-load:
    enabled: true
    clients:
      - userservice # 需要负载均衡的服务名